### ISSUE TITLE
Enable sentences with features

### ISSUE THREAD

**Issue by elpiel** [AeroRust/nmea#91]
We should have all sentences enabled with a feature, e.g. "all-sentences", however, it should be possible to parse only a subset of sentences by enabling only their own feature, e.g. `gll` or `gsv`, etc.

This will ensure that the size of the crate is optimised for highly constraint targets which require some subset of the sentences.

This is related to #54

**Comment by elpiel** [comment]
Valid point. Yes it will be, but we're bump version to `0.5`.
We can also include Changelog but I'm not afraid to break the build from minor version updates.

```toml
default = ["std", "all-sentences"]
all-sentences = ["...", "vendor-specific"]
vendor-specific = [".."]
...
..
.
```
